import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0 | clone by kev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* header  */}
      <Header />
      {/* nav */}
      <Nav />
      {/* main contents */}
      <Results />
    </div>
  );
}
